# NOTE:
# need only one ssm_master MPV
# need zero or one ts master MPV
MPV_config:
  - name: J1ADC
    ip_address: 192.168.1.20
    use: true
    ssm_master: true # start/stop signal
    ts_master: false # timestamp master

  - name: J1TDC
    ip_address: 192.168.1.21
    use: true
    ssm_master: false # start/stop signal
    ts_master: true # timestamp master

  - name: E7MPV
    ip_address: 192.168.1.22
    use: true
    ssm_master: false # start/stop signal
    ts_master: false # timestamp master

# NOTE:
# prepare the google spread sheet in advance
runsummary_config:
  sheetname: test_runsummary
  prinfo: /usr/babirl/ridfutil/prinfo
  scaler: false # send scaler info (currently not support)
